@url = https://localhost:7000

GET {{url}}/reservations

###
POST {{url}}/reservations
Content-Type: application/json

{
    "employeeName": "John Doe",
    "parkingSpotName": "P2",
    "licensePlate": "ABC1234"    
}

###
PUT {{url}}/reservations/1
Content-Type: application/json

{
    "licensePlate": "ABC1235"
}

###
DELETE {{url}}/reservations/2
